package CuestionariosModulos1Al4MasPruebaFinal;

import java.util.ArrayList;
import java.util.List;

public class BancoPreguntasSQL {

    static class Pregunta {
        int id; String grupo; String seccion; int numero; String enunciado; String respuesta;
        Pregunta(int id, String grupo, String seccion, int numero, String enunciado, String respuesta) {
            this.id=id; this.grupo=grupo; this.seccion=seccion; this.numero=numero; this.enunciado=enunciado; this.respuesta=respuesta;
        }
    }

    public static List<Pregunta> cargarPreguntas() {
        List<Pregunta> banco = new ArrayList<>();
        banco.add(new Pregunta(1, "Módulo 1", "1. Introducción a SQL", 1, "¿Qué significa SQL?", "Structured Query Language (Lenguaje de Consulta Estructurado)."));
        banco.add(new Pregunta(2, "Módulo 1", "1. Introducción a SQL", 2, "¿Para qué se utiliza SQL?", "Para definir, consultar, insertar, modificar y eliminar datos en bases de datos relacionales."));
        banco.add(new Pregunta(3, "Módulo 1", "1. Introducción a SQL", 3, "¿Qué es PostgreSQL?", "Un sistema gestor de bases de datos relacional y objeto-relacional."));
        banco.add(new Pregunta(4, "Módulo 1", "2. Sublenguajes SQL", 4, "¿Qué significa DDL?", "Data Definition Language. Define estructuras de la base. Ejemplos: CREATE, ALTER, DROP y TRUNCATE."));
        banco.add(new Pregunta(5, "Módulo 1", "2. Sublenguajes SQL", 5, "¿Qué significa DML?", "Data Manipulation Language. Manipula datos. Ejemplos: INSERT, UPDATE y DELETE."));
        banco.add(new Pregunta(6, "Módulo 1", "2. Sublenguajes SQL", 6, "¿Qué comando se utiliza principalmente para consultar datos?", "SELECT."));
        banco.add(new Pregunta(7, "Módulo 1", "2. Sublenguajes SQL", 7, "¿Qué significa DCL?", "Data Control Language. Ejemplos: GRANT y REVOKE."));
        banco.add(new Pregunta(8, "Módulo 1", "2. Sublenguajes SQL", 8, "¿Qué significa TCL?", "Transaction Control Language. Ejemplos: COMMIT, ROLLBACK y SAVEPOINT."));
        banco.add(new Pregunta(9, "Módulo 1", "3. Bases, esquemas y tablas", 9, "¿Qué sentencia crea una base de datos?", "CREATE DATABASE."));
        banco.add(new Pregunta(10, "Módulo 1", "3. Bases, esquemas y tablas", 10, "¿Qué sentencia crea un esquema?", "CREATE SCHEMA."));
        banco.add(new Pregunta(11, "Módulo 1", "3. Bases, esquemas y tablas", 11, "¿Qué sentencia crea una tabla?", "CREATE TABLE."));
        banco.add(new Pregunta(12, "Módulo 1", "3. Bases, esquemas y tablas", 12, "¿Qué sentencia modifica la estructura de una tabla?", "ALTER TABLE."));
        banco.add(new Pregunta(13, "Módulo 1", "3. Bases, esquemas y tablas", 13, "¿Qué sentencia elimina una tabla completa?", "DROP TABLE."));
        banco.add(new Pregunta(14, "Módulo 1", "4. Tipos de datos", 14, "¿Qué tipo usarías para un número entero?", "INTEGER / INT."));
        banco.add(new Pregunta(15, "Módulo 1", "4. Tipos de datos", 15, "¿Qué tipo usarías para texto de longitud variable?", "VARCHAR(n)."));
        banco.add(new Pregunta(16, "Módulo 1", "4. Tipos de datos", 16, "¿Qué tipo usarías para una fecha?", "DATE."));
        banco.add(new Pregunta(17, "Módulo 1", "4. Tipos de datos", 17, "¿Qué tipo usarías para importes con decimales?", "NUMERIC(p,s)."));
        banco.add(new Pregunta(18, "Módulo 1", "4. Tipos de datos", 18, "¿Qué hace SERIAL en PostgreSQL?", "Genera valores enteros autoincrementales, usado habitualmente en claves primarias."));
        banco.add(new Pregunta(19, "Módulo 1", "5. Restricciones / Constraints", 19, "¿Qué hace PRIMARY KEY?", "Identifica de forma única cada fila y no admite NULL."));
        banco.add(new Pregunta(20, "Módulo 1", "5. Restricciones / Constraints", 20, "¿Qué hace FOREIGN KEY?", "Relaciona una tabla con la clave de otra tabla."));
        banco.add(new Pregunta(21, "Módulo 1", "5. Restricciones / Constraints", 21, "¿Qué hace NOT NULL?", "Obliga a que una columna tenga un valor."));
        banco.add(new Pregunta(22, "Módulo 1", "5. Restricciones / Constraints", 22, "¿Qué hace UNIQUE?", "Impide valores repetidos."));
        banco.add(new Pregunta(23, "Módulo 1", "5. Restricciones / Constraints", 23, "¿Qué hace CHECK?", "Valida que los datos cumplan una condición."));
        banco.add(new Pregunta(24, "Módulo 1", "5. Restricciones / Constraints", 24, "¿Qué es una clave primaria compuesta?", "Una PRIMARY KEY formada por dos o más columnas."));
        banco.add(new Pregunta(25, "Módulo 1", "5. Restricciones / Constraints", 25, "¿Qué es un DOMAIN en PostgreSQL?", "Un tipo de dato personalizado con reglas o restricciones propias."));
        banco.add(new Pregunta(26, "Módulo 1", "6. INSERT", 26, "¿Qué sentencia se utiliza para insertar registros?", "INSERT INTO."));
        banco.add(new Pregunta(27, "Módulo 1", "6. INSERT", 27, "¿Se pueden insertar varias filas con un solo INSERT?", "Sí, separando los grupos de valores con comas."));
        banco.add(new Pregunta(28, "Módulo 1", "7. SELECT", 28, "¿Qué hace SELECT *?", "Devuelve todas las columnas."));
        banco.add(new Pregunta(29, "Módulo 1", "7. SELECT", 29, "¿Qué cláusula indica de qué tabla se obtienen los datos?", "FROM."));
        banco.add(new Pregunta(30, "Módulo 1", "7. SELECT", 30, "¿Qué cláusula filtra filas?", "WHERE."));
        banco.add(new Pregunta(31, "Módulo 1", "7. SELECT", 31, "¿Qué operador comprueba igualdad?", "="));
        banco.add(new Pregunta(32, "Módulo 1", "7. SELECT", 32, "¿Qué operador significa diferente?", "<> o !="));
        banco.add(new Pregunta(33, "Módulo 1", "8. Filtros básicos", 33, "¿Qué hace BETWEEN?", "Filtra valores dentro de un rango inclusivo."));
        banco.add(new Pregunta(34, "Módulo 1", "8. Filtros básicos", 34, "¿Qué hace IN?", "Comprueba si un valor pertenece a una lista."));
        banco.add(new Pregunta(35, "Módulo 1", "8. Filtros básicos", 35, "¿Qué hace LIKE?", "Busca patrones de texto. % representa cero o más caracteres y _ exactamente uno."));
        banco.add(new Pregunta(36, "Módulo 1", "8. Filtros básicos", 36, "¿Qué diferencia hay entre LIKE e ILIKE?", "ILIKE no distingue mayúsculas de minúsculas."));
        banco.add(new Pregunta(37, "Módulo 1", "8. Filtros básicos", 37, "¿Cómo se comprueba un valor NULL?", "IS NULL / IS NOT NULL."));
        banco.add(new Pregunta(38, "Módulo 1", "9. UPDATE y DELETE", 38, "¿Qué sentencia modifica datos existentes?", "UPDATE."));
        banco.add(new Pregunta(39, "Módulo 1", "9. UPDATE y DELETE", 39, "¿Qué sentencia elimina filas?", "DELETE."));
        banco.add(new Pregunta(40, "Módulo 1", "9. UPDATE y DELETE", 40, "¿Por qué es importante WHERE en UPDATE o DELETE?", "Porque sin WHERE se modifican o eliminan todas las filas."));
        banco.add(new Pregunta(41, "Módulo 1", "10. DELETE, TRUNCATE y DROP", 41, "¿Qué hace DELETE?", "Elimina filas y puede utilizar WHERE."));
        banco.add(new Pregunta(42, "Módulo 1", "10. DELETE, TRUNCATE y DROP", 42, "¿Qué hace TRUNCATE?", "Vacía rápidamente todas las filas de una tabla."));
        banco.add(new Pregunta(43, "Módulo 1", "10. DELETE, TRUNCATE y DROP", 43, "¿Qué hace DROP?", "Elimina el objeto completo, incluida su estructura."));
        banco.add(new Pregunta(44, "Módulo 2", "C1 - 1.1 Expresiones regulares", 1, "¿Cuál opción coincide con cualquier cadena que termina con 'abc'?", "d) 'abc$'"));
        banco.add(new Pregunta(45, "Módulo 2", "C1 - 1.1 Expresiones regulares", 2, "¿Cuál NO es una función o característica de las expresiones regulares?", "c) Crear nuevos registros."));
        banco.add(new Pregunta(46, "Módulo 2", "C1 - 1.1 Expresiones regulares", 3, "¿Cuál operador es insensible a mayúsculas y minúsculas en PostgreSQL?", "b) ILIKE. Nota: ~* también es case-insensitive para regex."));
        banco.add(new Pregunta(47, "Módulo 2", "C1 - 1.1 Expresiones regulares", 4, "¿Cómo extraer un número de 'Order #1234'?", "regexp_matches con \\d+."));
        banco.add(new Pregunta(48, "Módulo 2", "C1 - 1.1 Expresiones regulares", 5, "¿Qué significa [] en una expresión regular?", "d) Coincide con cualquier carácter dentro del conjunto."));
        banco.add(new Pregunta(49, "Módulo 2", "C1 - 1.1 Expresiones regulares", 6, "¿Qué operador indica una o más apariciones?", "c) +"));
        banco.add(new Pregunta(50, "Módulo 2", "C1 - 1.1 Expresiones regulares", 7, "¿Qué significa NOT ILIKE?", "a) Busca patrones que no coincidan sin distinguir mayúsculas/minúsculas."));
        banco.add(new Pregunta(51, "Módulo 2", "C1 - 1.1 Expresiones regulares", 8, "¿Qué simboliza ^ ?", "b) Inicio de una cadena."));
        banco.add(new Pregunta(52, "Módulo 2", "C1 - 1.1 Expresiones regulares", 9, "¿Cómo buscar un nombre que comienza con cualquier carácter seguido de 'bc'?", "Usando ILIKE '_bc'."));
        banco.add(new Pregunta(53, "Módulo 2", "C1 - 1.1 Expresiones regulares", 10, "¿Cómo se niega un conjunto de caracteres?", "c) [^]"));
        banco.add(new Pregunta(54, "Módulo 2", "C2 - 1.2 Funciones de agregación", 1, "Contar todas las filas de empleados.", "c) COUNT(*)."));
        banco.add(new Pregunta(55, "Módulo 2", "C2 - 1.2 Funciones de agregación", 2, "Sumar precios de Electrónica y Libros.", "d) SUM con WHERE IN."));
        banco.add(new Pregunta(56, "Módulo 2", "C2 - 1.2 Funciones de agregación", 3, "Obtener salario máximo del departamento Ventas.", "b) MAX."));
        banco.add(new Pregunta(57, "Módulo 2", "C2 - 1.2 Funciones de agregación", 4, "Obtener el total de precios no nulos.", "c) SUM(precio)."));
        banco.add(new Pregunta(58, "Módulo 2", "C2 - 1.2 Funciones de agregación", 5, "Contar empleados con salario superior a 2000.", "a) COUNT(*) FILTER."));
        banco.add(new Pregunta(59, "Módulo 2", "C2 - 1.2 Funciones de agregación", 6, "Obtener precio mínimo.", "c) MIN(precio)."));
        banco.add(new Pregunta(60, "Módulo 2", "C2 - 1.2 Funciones de agregación", 7, "Promedio de edad en departamento IT.", "b) AVG(edad)."));
        banco.add(new Pregunta(61, "Módulo 2", "C2 - 1.2 Funciones de agregación", 8, "Contar valores no nulos de una columna.", "c) COUNT(columna)."));
        banco.add(new Pregunta(62, "Módulo 2", "C2 - 1.2 Funciones de agregación", 9, "¿Cuál NO es función de agregación: MAX, SUM, COUNT o FILTER?", "d) FILTER."));
        banco.add(new Pregunta(63, "Módulo 2", "C2 - 1.2 Funciones de agregación", 10, "Obtener salario máximo y mínimo.", "a) MAX y MIN."));
        banco.add(new Pregunta(64, "Módulo 2", "C3 - 1.3 Funciones de grupo", 1, "Categorías con más de 10 productos distintos.", "b) GROUP BY + HAVING COUNT(DISTINCT ...)."));
        banco.add(new Pregunta(65, "Módulo 2", "C3 - 1.3 Funciones de grupo", 2, "Años con más de 100 unidades vendidas.", "b) GROUP BY año + HAVING SUM(cantidad) > 100."));
        banco.add(new Pregunta(66, "Módulo 2", "C3 - 1.3 Funciones de grupo", 3, "Agrupar empleados por departamento y sumar salarios.", "c) GROUP BY departamento."));
        banco.add(new Pregunta(67, "Módulo 2", "C3 - 1.3 Funciones de grupo", 4, "¿Qué cláusula filtra grupos con más de 5 miembros?", "d) HAVING."));
        banco.add(new Pregunta(68, "Módulo 2", "C3 - 1.3 Funciones de grupo", 5, "Departamentos con salario promedio superior a 2000.", "b) HAVING AVG(salario) > 2000."));
        banco.add(new Pregunta(69, "Módulo 2", "C3 - 1.3 Funciones de grupo", 6, "Ordenar nombres por edad descendente.", "c) ORDER BY edad DESC."));
        banco.add(new Pregunta(70, "Módulo 2", "C3 - 1.3 Funciones de grupo", 7, "Departamentos con al menos 3 empleados y suma de salarios mayor al promedio.", "d) GROUP BY + HAVING."));
        banco.add(new Pregunta(71, "Módulo 2", "C3 - 1.3 Funciones de grupo", 8, "Clientes con más de 5 pedidos.", "c) GROUP BY cliente_id + HAVING COUNT(...) > 5."));
        banco.add(new Pregunta(72, "Módulo 2", "C3 - 1.3 Funciones de grupo", 9, "¿Qué devuelve GROUP BY sin función de agregación?", "b) Una lista de valores únicos para las columnas especificadas."));
        banco.add(new Pregunta(73, "Módulo 2", "C3 - 1.3 Funciones de grupo", 10, "Departamentos con más de 30 empleados.", "b) HAVING COUNT(*) > 30."));
        banco.add(new Pregunta(74, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 1, "¿Qué ventaja tiene LIMIT en consultas grandes?", "d) Reduce la cantidad de datos transferidos desde el servidor."));
        banco.add(new Pregunta(75, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 2, "Obtener las primeras 3 filas.", "c) LIMIT 3."));
        banco.add(new Pregunta(76, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 3, "Con DISTINCT ON, ¿cómo se elige el primer registro según un criterio?", "c) Ordenando con ORDER BY."));
        banco.add(new Pregunta(77, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 4, "¿Qué hace DISTINCT?", "c) Elimina filas duplicadas del resultado."));
        banco.add(new Pregunta(78, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 5, "Obtener nombres únicos.", "b) SELECT DISTINCT nombre."));
        banco.add(new Pregunta(79, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 6, "Obtener los primeros 5 productos.", "b) LIMIT 5."));
        banco.add(new Pregunta(80, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 7, "Obtener el número de categorías únicas.", "a) COUNT(DISTINCT categoria)."));
        banco.add(new Pregunta(81, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 8, "¿Cuál es la función de DISTINCT ON?", "b) Todas las anteriores son correctas (según el cuestionario)."));
        banco.add(new Pregunta(82, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 9, "Obtener el primer pedido de cada cliente ordenado por fecha.", "d) DISTINCT ON + ORDER BY."));
        banco.add(new Pregunta(83, "Módulo 2", "C4 - 1.4 DISTINCT y LIMIT", 10, "Obtener los dos clientes más recientes.", "c) ORDER BY fecha_registro DESC LIMIT 2."));
        banco.add(new Pregunta(84, "Módulo 2", "C5 - Joins", 1, "¿Qué JOIN devuelve solo coincidencias?", "b) INNER JOIN."));
        banco.add(new Pregunta(85, "Módulo 2", "C5 - Joins", 2, "¿Qué es un producto cartesiano?", "c) Todas las combinaciones posibles entre filas de dos tablas."));
        banco.add(new Pregunta(86, "Módulo 2", "C5 - Joins", 3, "¿Qué JOIN devuelve todos los empleados y solo departamentos coincidentes?", "b) LEFT JOIN."));
        banco.add(new Pregunta(87, "Módulo 2", "C5 - Joins", 4, "¿Qué JOIN devuelve todos los registros de la derecha y coincidencias de la izquierda?", "b) RIGHT JOIN."));
        banco.add(new Pregunta(88, "Módulo 2", "C5 - Joins", 5, "¿Qué JOIN genera todas las combinaciones posibles?", "a) CROSS JOIN."));
        banco.add(new Pregunta(89, "Módulo 2", "C5 - Joins", 6, "¿Qué JOIN devuelve todos los registros de ambas tablas y NULL donde no hay coincidencia?", "b) FULL JOIN."));
        banco.add(new Pregunta(90, "Módulo 2", "C5 - Joins", 7, "¿Qué ocurre en un INNER JOIN cuando no existe coincidencia?", "b) La fila no se incluye en el resultado."));
        banco.add(new Pregunta(91, "Módulo 2", "C5 - Joins", 8, "¿Qué devuelve un FULL JOIN entre productos y pedidos?", "a) Todas las filas de ambas tablas con NULL donde no hay coincidencias."));
        banco.add(new Pregunta(92, "Módulo 2", "C5 - Joins", 9, "Principal ventaja de JOIN frente a múltiples consultas.", "b) Mejora en la eficiencia de la consulta."));
        banco.add(new Pregunta(93, "Módulo 2", "C5 - Joins", 10, "¿Qué hace RIGHT JOIN?", "b) Retorna todos los registros de la tabla derecha, con NULL donde no hay coincidencia."));
        banco.add(new Pregunta(94, "Módulo 2", "C6 - 1.6 Subconsultas", 1, "¿Qué es una subconsulta?", "b) Una consulta dentro de otra consulta."));
        banco.add(new Pregunta(95, "Módulo 2", "C6 - 1.6 Subconsultas", 2, "Productos con ingresos superiores a 5000.", "b) Subconsulta con IN, GROUP BY y HAVING."));
        banco.add(new Pregunta(96, "Módulo 2", "C6 - 1.6 Subconsultas", 3, "¿Dónde pueden usarse subconsultas?", "b) SELECT, FROM y WHERE."));
        banco.add(new Pregunta(97, "Módulo 2", "C6 - 1.6 Subconsultas", 4, "¿Cómo se denomina una subconsulta usada como tabla dentro de FROM?", "Subconsulta derivada (derived table). En el cuestionario la opción esperada era a) Ninguna de las anteriores."));
        banco.add(new Pregunta(98, "Módulo 2", "C6 - 1.6 Subconsultas", 5, "Clientes con pedidos mayores a 1000.", "d) IN con subconsulta."));
        banco.add(new Pregunta(99, "Módulo 2", "C6 - 1.6 Subconsultas", 6, "Clientes cuyo total de pedidos supera 1000.", "d) GROUP BY + HAVING SUM(monto)."));
        banco.add(new Pregunta(100, "Módulo 2", "C6 - 1.6 Subconsultas", 7, "¿Qué es una subconsulta escalar?", "a) Devuelve exactamente un valor."));
        banco.add(new Pregunta(101, "Módulo 2", "C6 - 1.6 Subconsultas", 8, "¿Qué hace EXISTS?", "b) Devuelve TRUE si la subconsulta contiene filas."));
        banco.add(new Pregunta(102, "Módulo 2", "C6 - 1.6 Subconsultas", 9, "Clientes con pedidos pendientes.", "b) EXISTS correlacionado."));
        banco.add(new Pregunta(103, "Módulo 2", "C6 - 1.6 Subconsultas", 10, "Característica de una subconsulta correlacionada.", "c) Hace referencia a columnas de la consulta exterior."));
        banco.add(new Pregunta(104, "Módulo 2", "C7 - 1.7 Funciones de texto", 1, "¿Qué función extrae los primeros N caracteres?", "c) LEFT."));
        banco.add(new Pregunta(105, "Módulo 2", "C7 - 1.7 Funciones de texto", 2, "¿Qué función combina varias columnas/cadenas?", "d) CONCAT."));
        banco.add(new Pregunta(106, "Módulo 2", "C7 - 1.7 Funciones de texto", 3, "Últimos 5 caracteres de 'Bienvenidos'.", "b) RIGHT."));
        banco.add(new Pregunta(107, "Módulo 2", "C7 - 1.7 Funciones de texto", 4, "¿Qué hace CONCAT?", "b) Une dos o más cadenas en una."));
        banco.add(new Pregunta(108, "Módulo 2", "C7 - 1.7 Funciones de texto", 5, "Longitud de 'computadora'.", "c) LENGTH."));
        banco.add(new Pregunta(109, "Módulo 2", "C7 - 1.7 Funciones de texto", 6, "Reemplazar 'cielo' por 'mar'.", "c) REPLACE."));
        banco.add(new Pregunta(110, "Módulo 2", "C7 - 1.7 Funciones de texto", 7, "Concatenar nombre y apellido con un espacio.", "c) CONCAT."));
        banco.add(new Pregunta(111, "Módulo 2", "C7 - 1.7 Funciones de texto", 8, "¿Qué función permite comparar longitudes?", "c) LENGTH."));
        banco.add(new Pregunta(112, "Módulo 2", "C7 - 1.7 Funciones de texto", 9, "Primeros 3 caracteres de cada nombre.", "c) LEFT(nombre,3)."));
        banco.add(new Pregunta(113, "Módulo 2", "C7 - 1.7 Funciones de texto", 10, "Reemplazar 'viejo' por 'nuevo' en una descripción.", "c) REPLACE."));
        banco.add(new Pregunta(114, "Módulo 2", "C8 - 1.8 Funciones de fecha", 1, "Tipo de dato para almacenar solo fecha.", "b) DATE."));
        banco.add(new Pregunta(115, "Módulo 2", "C8 - 1.8 Funciones de fecha", 2, "DATE_PART minute de 15:30:45.", "c) 30."));
        banco.add(new Pregunta(116, "Módulo 2", "C8 - 1.8 Funciones de fecha", 3, "¿Qué hace DATE_PART?", "a) Extrae una parte específica de una fecha o timestamp."));
        banco.add(new Pregunta(117, "Módulo 2", "C8 - 1.8 Funciones de fecha", 4, "Extraer el año de 2023-12-25.", "d) DATE_PART year."));
        banco.add(new Pregunta(118, "Módulo 2", "C8 - 1.8 Funciones de fecha", 5, "Extraer el mes de fecha_registro.", "a) DATE_PART month."));
        banco.add(new Pregunta(119, "Módulo 2", "C8 - 1.8 Funciones de fecha", 6, "Día de 2024-02-29.", "b) 29."));
        banco.add(new Pregunta(120, "Módulo 2", "C8 - 1.8 Funciones de fecha", 7, "Extraer segundos de 12:59:59.", "c) DATE_PART second."));
        banco.add(new Pregunta(121, "Módulo 2", "C8 - 1.8 Funciones de fecha", 8, "Tipo con fecha, hora y zona horaria.", "c) TIMESTAMPTZ."));
        banco.add(new Pregunta(122, "Módulo 2", "C8 - 1.8 Funciones de fecha", 9, "Extraer hora.", "c) DATE_PART hour."));
        banco.add(new Pregunta(123, "Módulo 2", "C8 - 1.8 Funciones de fecha", 10, "Extraer trimestre.", "d) DATE_PART quarter."));
        banco.add(new Pregunta(124, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 1, "¿Qué comando se utiliza para crear un usuario en PostgreSQL?", "c) CREATE ROLE nombre_usuario WITH LOGIN PASSWORD 'contraseña';"));
        banco.add(new Pregunta(125, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 2, "¿Cómo revocarías el privilegio de ejecutar procedimientos almacenados de un usuario específico?", "c) REVOKE EXECUTE ON ALL PROCEDURES IN SCHEMA public FROM usuario;"));
        banco.add(new Pregunta(126, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 3, "¿Qué es un rol en PostgreSQL?", "b) Una colección de privilegios asignable a usuarios o grupos."));
        banco.add(new Pregunta(127, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 4, "¿Cómo se concede SELECT en una tabla específica a un usuario?", "b) GRANT SELECT ON TABLE tabla TO usuario;"));
        banco.add(new Pregunta(128, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 5, "¿Qué comando se usa para eliminar un rol?", "a) DROP ROLE nombre_rol;"));
        banco.add(new Pregunta(129, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 6, "¿Cuál NO es un privilegio directamente relacionado con tablas?", "c) CONNECT."));
        banco.add(new Pregunta(130, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 7, "¿Cómo revocar todos los privilegios de un usuario en una tabla?", "a) REVOKE ALL ON TABLE tabla FROM usuario;"));
        banco.add(new Pregunta(131, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 8, "¿Qué sintaxis transfiere la propiedad de una tabla a otro rol?", "c) ALTER TABLE tabla OWNER TO nuevo_rol;"));
        banco.add(new Pregunta(132, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 9, "¿Para qué se utiliza principalmente USAGE?", "a) Para permitir acceso y uso de esquemas y secuencias."));
        banco.add(new Pregunta(133, "Módulo 3", "C1 - 2.1 Roles, Usuarios y Privilegios", 10, "¿Cómo asignas un rol existente a un usuario?", "d) GRANT rol TO usuario;"));
        banco.add(new Pregunta(134, "Módulo 3", "C2 - 2.2 Transacciones", 1, "¿Qué comando se utiliza para iniciar una transacción?", "c) BEGIN;"));
        banco.add(new Pregunta(135, "Módulo 3", "C2 - 2.2 Transacciones", 2, "¿Qué serie de comandos permite probar inserciones y revertirlas si algo sale mal?", "b) BEGIN; ... ROLLBACK;"));
        banco.add(new Pregunta(136, "Módulo 3", "C2 - 2.2 Transacciones", 3, "¿Qué propiedad garantiza que todos los cambios se reviertan si la transacción falla?", "a) Atomicidad."));
        banco.add(new Pregunta(137, "Módulo 3", "C2 - 2.2 Transacciones", 4, "¿Qué comando confirma y hace permanentes los cambios?", "b) COMMIT;"));
        banco.add(new Pregunta(138, "Módulo 3", "C2 - 2.2 Transacciones", 5, "¿Qué comando revierte una transacción antes de confirmarla?", "b) ROLLBACK;"));
        banco.add(new Pregunta(139, "Módulo 3", "C2 - 2.2 Transacciones", 6, "¿Cómo se llama dividir una transacción mediante puntos de guardado?", "c) Savepointing."));
        banco.add(new Pregunta(140, "Módulo 3", "C2 - 2.2 Transacciones", 7, "¿Qué comando establece un punto de guardado?", "c) SAVEPOINT savepoint_name;"));
        banco.add(new Pregunta(141, "Módulo 3", "C2 - 2.2 Transacciones", 8, "¿Qué propiedad asegura que los efectos confirmados sean permanentes?", "c) Durabilidad."));
        banco.add(new Pregunta(142, "Módulo 3", "C2 - 2.2 Transacciones", 9, "¿Qué comando deshace los cambios desde un punto de guardado?", "b) ROLLBACK TO savepoint_name;"));
        banco.add(new Pregunta(143, "Módulo 3", "C2 - 2.2 Transacciones", 10, "¿Qué comando no pertenece al manejo de transacciones: COMMIT, BEGIN, INSERT o REVOKE?", "d) REVOKE."));
        banco.add(new Pregunta(144, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 1, "¿Para qué ejecutar pg_terminate_backend() antes de DROP DATABASE?", "a) Cerrar conexiones activas que impiden borrar la base."));
        banco.add(new Pregunta(145, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 2, "¿Cuál es el propósito del parámetro TEMPLATE al crear una base?", "d) Reutilizar la estructura y contenido de otra base."));
        banco.add(new Pregunta(146, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 3, "¿Cuál es la función de LC_COLLATE?", "c) Controlar cómo se ordenan los textos."));
        banco.add(new Pregunta(147, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 4, "¿Qué comando cambia el nombre de una base?", "d) ALTER DATABASE nombre RENAME TO nuevo_nombre;"));
        banco.add(new Pregunta(148, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 5, "¿Qué comando crea una nueva base?", "b) CREATE DATABASE nombre;"));
        banco.add(new Pregunta(149, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 6, "¿Cómo eliminar una base solo si existe?", "b) DROP DATABASE IF EXISTS nombre;"));
        banco.add(new Pregunta(150, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 7, "¿Qué instrucción establece un parámetro de configuración en una base existente?", "d) ALTER DATABASE nombre SET parámetro TO valor;"));
        banco.add(new Pregunta(151, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 8, "¿Qué instrucción restablece un parámetro a su valor predeterminado?", "c) ALTER DATABASE nombre RESET parámetro;"));
        banco.add(new Pregunta(152, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 9, "¿Qué parámetro define el tablespace de una nueva base?", "d) TABLESPACE."));
        banco.add(new Pregunta(153, "Módulo 3", "C3 - 2.3 Comandos de Alta, Baja y Modificación", 10, "¿Qué parámetro asigna el propietario al crear una base?", "b) OWNER."));
        banco.add(new Pregunta(154, "Módulo 3", "C4 - 2.4 Vistas", 1, "¿Qué sentencia crea una vista en PostgreSQL?", "d) CREATE VIEW nombre_vista AS SELECT ..."));
        banco.add(new Pregunta(155, "Módulo 3", "C4 - 2.4 Vistas", 2, "¿Cómo puede un DBA asegurarse de que solo cambios validados sean visibles a través de una vista?", "d) Utilizando disparadores (triggers) para controlar la visibilidad, según el cuestionario."));
        banco.add(new Pregunta(156, "Módulo 3", "C4 - 2.4 Vistas", 3, "¿Cuál es el propósito principal de una vista?", "b) Actuar como tabla virtual para simplificar consultas complejas."));
        banco.add(new Pregunta(157, "Módulo 3", "C4 - 2.4 Vistas", 4, "¿Cómo se consulta una vista?", "c) SELECT * FROM nombre_vista;"));
        banco.add(new Pregunta(158, "Módulo 3", "C4 - 2.4 Vistas", 5, "¿Cómo modificar una vista para incluir una nueva columna?", "a) CREATE OR REPLACE VIEW ..."));
        banco.add(new Pregunta(159, "Módulo 3", "C4 - 2.4 Vistas", 6, "¿Qué comando elimina una vista?", "d) DROP VIEW nombre_vista;"));
        banco.add(new Pregunta(160, "Módulo 3", "C4 - 2.4 Vistas", 7, "¿Cómo evitar error si la vista no existe al eliminarla?", "b) DROP VIEW IF EXISTS nombre_vista;"));
        banco.add(new Pregunta(161, "Módulo 3", "C4 - 2.4 Vistas", 8, "¿Cómo conceder SELECT en una vista a un usuario?", "b) GRANT SELECT ON nombre_vista TO usuario;"));
        banco.add(new Pregunta(162, "Módulo 3", "C4 - 2.4 Vistas", 9, "¿Cómo revocar SELECT en una vista?", "b) REVOKE SELECT ON nombre_vista FROM usuario;"));
        banco.add(new Pregunta(163, "Módulo 3", "C4 - 2.4 Vistas", 10, "Al usar CREATE OR REPLACE VIEW y omitir una columna existente, ¿qué ocurre?", "PostgreSQL no permite quitarla de ese modo; la nueva definición debe conservar las columnas existentes. Si el cuestionario obliga a elegir, suele esperar d) Se mantiene en la vista."));
        banco.add(new Pregunta(164, "Módulo 3", "C5 - 2.5 Índices", 1, "¿Qué comando crea un índice B-tree en una columna?", "a) CREATE INDEX nombre_indice ON nombre_tabla (columna);"));
        banco.add(new Pregunta(165, "Módulo 3", "C5 - 2.5 Índices", 2, "¿Qué nivel de detalle se mencionó para registrar operaciones que involucran índices?", "c) DEBUG1 (respuesta del cuestionario)."));
        banco.add(new Pregunta(166, "Módulo 3", "C5 - 2.5 Índices", 3, "¿Cuál es la principal ventaja de usar índices?", "a) Mejorar la velocidad de las consultas."));
        banco.add(new Pregunta(167, "Módulo 3", "C5 - 2.5 Índices", 4, "¿Qué índice es especialmente útil para condiciones de igualdad?", "d) Hash."));
        banco.add(new Pregunta(168, "Módulo 3", "C5 - 2.5 Índices", 5, "¿Cómo crear un índice de múltiples columnas?", "c) CREATE INDEX nombre_indice ON nombre_tabla (columna1, columna2);"));
        banco.add(new Pregunta(169, "Módulo 3", "C5 - 2.5 Índices", 6, "¿Cómo eliminar un índice evitando error si no existe?", "c) DROP INDEX IF EXISTS nombre_indice;"));
        banco.add(new Pregunta(170, "Módulo 3", "C5 - 2.5 Índices", 7, "¿Qué índice se recomienda para datos geoespaciales?", "a) GiST."));
        banco.add(new Pregunta(171, "Módulo 3", "C5 - 2.5 Índices", 8, "¿Qué índice es adecuado para búsqueda de texto completo y arrays?", "a) GIN."));
        banco.add(new Pregunta(172, "Módulo 3", "C5 - 2.5 Índices", 9, "¿Cómo definir explícitamente un índice HASH?", "d) CREATE INDEX ... USING HASH (...);"));
        banco.add(new Pregunta(173, "Módulo 3", "C5 - 2.5 Índices", 10, "¿Para qué sirve DROP INDEX [IF EXISTS] nombre_indice [CASCADE | RESTRICT]?", "b) Para eliminar un índice y opcionalmente eliminar dependencias o restringir si existen."));
        banco.add(new Pregunta(174, "Módulo 3", "C6 - 2.6 Tablespace", 1, "¿Qué comando crea un tablespace?", "d) CREATE TABLESPACE nombre_tablespace LOCATION 'ruta_directorio';"));
        banco.add(new Pregunta(175, "Módulo 3", "C6 - 2.6 Tablespace", 2, "¿Para qué se utiliza principalmente un tablespace?", "b) Para distribuir datos en diferentes dispositivos/ubicaciones de almacenamiento y mejorar el rendimiento."));
        banco.add(new Pregunta(176, "Módulo 3", "C6 - 2.6 Tablespace", 3, "¿Qué privilegio necesita un usuario para crear objetos en un tablespace que no le pertenece?", "c) CREATE."));
        banco.add(new Pregunta(177, "Módulo 3", "C6 - 2.6 Tablespace", 4, "¿Qué comando cambia el propietario de un tablespace?", "d) ALTER TABLESPACE nombre_tablespace OWNER TO nuevo_propietario;"));
        banco.add(new Pregunta(178, "Módulo 3", "C6 - 2.6 Tablespace", 5, "¿Cómo eliminar un tablespace evitando error si no existe?", "c) DROP TABLESPACE IF EXISTS nombre_tablespace;"));
        banco.add(new Pregunta(179, "Módulo 3", "C6 - 2.6 Tablespace", 6, "¿Qué parámetro especifica la ubicación física del tablespace?", "c) LOCATION."));
        banco.add(new Pregunta(180, "Módulo 3", "C6 - 2.6 Tablespace", 7, "¿Cómo listar tablespaces con propietario y ubicación?", "d) Consultando pg_tablespace con pg_get_userbyid y pg_tablespace_location."));
        banco.add(new Pregunta(181, "Módulo 3", "C6 - 2.6 Tablespace", 8, "¿Qué ocurre si intentas eliminar un tablespace que contiene objetos?", "a) PostgreSQL no permite eliminarlo y muestra un error."));
        banco.add(new Pregunta(182, "Módulo 3", "C6 - 2.6 Tablespace", 9, "¿Cómo crear una tabla en un tablespace específico?", "c) CREATE TABLE ... TABLESPACE nombre_tablespace;"));
        banco.add(new Pregunta(183, "Módulo 3", "C6 - 2.6 Tablespace", 10, "¿Qué requisito debe cumplir el directorio del tablespace?", "c) Debe existir, estar vacío y ser propiedad del usuario de PostgreSQL."));
        banco.add(new Pregunta(184, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 1, "¿Qué archivo permite ajustar parámetros para generación de logs?", "a) postgresql.conf."));
        banco.add(new Pregunta(185, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 2, "¿Qué configurar para registrar la duración de todas las consultas?", "c) log_duration = on."));
        banco.add(new Pregunta(186, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 3, "¿Qué parámetro habilita el recolector de logs?", "c) logging_collector = on."));
        banco.add(new Pregunta(187, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 4, "¿Qué configuración incluye fecha y hora en el nombre del log?", "d) log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'."));
        banco.add(new Pregunta(188, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 5, "¿Cómo reiniciar el servicio PostgreSQL desde línea de comandos en Windows?", "a) net stop ... && net start ..."));
        banco.add(new Pregunta(189, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 6, "¿Qué parámetro define el tamaño máximo antes de rotar un log?", "d) log_rotation_size = '10MB'."));
        banco.add(new Pregunta(190, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 7, "¿Qué parámetro registra solo WARNING o superior?", "a) log_min_messages = 'WARNING'."));
        banco.add(new Pregunta(191, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 8, "¿Cómo se especifica la ubicación donde se guardan los logs?", "d) log_directory = 'log'."));
        banco.add(new Pregunta(192, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 9, "¿Qué parámetro registra consultas que exceden 1000 ms?", "b) log_min_duration_statement = 1000."));
        banco.add(new Pregunta(193, "Módulo 3", "C7 - 2.7 Archivos Logs, Reinicio", 10, "¿Qué comando cambia el destino a stderr, csvlog y jsonlog?", "a) log_destination = 'stderr,csvlog,jsonlog'."));
        banco.add(new Pregunta(194, "Módulo 4", "C1 - PL/pgSQL y parámetros de una función", 1, "¿Cómo se realiza un comentario de una línea?", "c) -- (símbolos doble guion)."));
        banco.add(new Pregunta(195, "Módulo 4", "C1 - PL/pgSQL y parámetros de una función", 2, "¿Cuál atributo se declara en una variable y toma el tipo de dato de una columna de la tabla referenciada?", "b) %TYPE"));
        banco.add(new Pregunta(196, "Módulo 4", "C1 - PL/pgSQL y parámetros de una función", 3, "¿Cuál de las siguientes es el objetivo primordial de PL/pgSQL?", "d) Implementar funciones y disparadores."));
        banco.add(new Pregunta(197, "Módulo 4", "C1 - PL/pgSQL y parámetros de una función", 4, "¿Cuál es el comando que se utiliza para definir una función en PL/pgSQL?", "c) CREATE FUNCTION"));
        banco.add(new Pregunta(198, "Módulo 4", "C1 - PL/pgSQL y parámetros de una función", 5, "¿Cuál es el parámetro que se pasa por función y puede cambiar su valor?", "c) INOUT"));
        banco.add(new Pregunta(199, "Módulo 4", "C1 - PL/pgSQL y parámetros de una función", 6, "¿Cuál es la principal ventaja de ejecutar un procedimiento en el servidor de base de datos?", "b) Mejora el rendimiento."));
        banco.add(new Pregunta(200, "Módulo 4", "C2 - Estructuras de Control en SQL", 1, "Mientras la condición sigue siendo evaluada como TRUE, ¿cuál es el tipo de bucle que se ejecuta?", "b) WHILE"));
        banco.add(new Pregunta(201, "Módulo 4", "C2 - Estructuras de Control en SQL", 2, "¿Cuál es la estructura del bucle FOR?", "c) FOR variable IN valor_minimo TO valor_maximo LOOP"));
        banco.add(new Pregunta(202, "Módulo 4", "C2 - Estructuras de Control en SQL", 3, "¿Cuál es la estructura del bucle WHILE?", "b) WHILE condicion LOOP"));
        banco.add(new Pregunta(203, "Módulo 4", "C2 - Estructuras de Control en SQL", 4, "¿Cuál es la palabra reservada que se utiliza para agregar condiciones adicionales a una estructura IF?", "d) ELSE (respuesta del cuestionario)."));
        banco.add(new Pregunta(204, "Módulo 4", "C2 - Estructuras de Control en SQL", 5, "¿Cuál es la sentencia utilizada para forzar la ejecución de un bucle LOOP?", "c) EXIT"));
        banco.add(new Pregunta(205, "Módulo 4", "C2 - Estructuras de Control en SQL", 6, "¿Cuál estructura de control se utiliza para manejar múltiples condiciones con resultados distintos?", "a) CASE."));
        banco.add(new Pregunta(206, "Módulo 4", "C3 - Gestión de Procedimientos y Funciones en SQL", 1, "¿Cómo se ejecuta un procedimiento?", "a) CALL nombre_procedimiento"));
        banco.add(new Pregunta(207, "Módulo 4", "C3 - Gestión de Procedimientos y Funciones en SQL", 2, "¿Cuál de las siguientes es el propósito principal de los procedimientos?", "a) Realizar tareas específicas como inserción de datos."));
        banco.add(new Pregunta(208, "Módulo 4", "C3 - Gestión de Procedimientos y Funciones en SQL", 3, "En un procedimiento, ¿cuál es la sentencia que se utiliza para iniciar un bloque de código?", "a) BEGIN"));
        banco.add(new Pregunta(209, "Módulo 4", "C3 - Gestión de Procedimientos y Funciones en SQL", 4, "¿Cuál es la instrucción que me permite mostrar un mensaje en pantalla?", "c) RAISE NOTICE"));
        banco.add(new Pregunta(210, "Módulo 4", "C3 - Gestión de Procedimientos y Funciones en SQL", 5, "¿Cuál es la palabra reservada utilizada para eliminar un procedimiento?", "a) DROP"));
        banco.add(new Pregunta(211, "Módulo 4", "C3 - Gestión de Procedimientos y Funciones en SQL", 6, "¿Cuál es la principal diferencia entre un procedimiento y una función?", "c) Los procedimientos no necesariamente devuelven un valor."));
        banco.add(new Pregunta(212, "Módulo 4", "C4 - TRIGGER", 1, "¿Cuál de las siguientes opciones es la mejor definición para un trigger?", "d) Un bloque de código que se ejecuta automáticamente al generar un evento en la base de datos."));
        banco.add(new Pregunta(213, "Módulo 4", "C4 - TRIGGER", 2, "¿Cuál de las siguientes opciones es un tipo de trigger que se ejecuta por cada fila afectada?", "b) ROW"));
        banco.add(new Pregunta(214, "Módulo 4", "C4 - TRIGGER", 3, "¿Cuál de las siguientes opciones es una sentencia para la eliminación de un trigger?", "c) DROP TRIGGER"));
        banco.add(new Pregunta(215, "Módulo 4", "C4 - TRIGGER", 4, "¿Cuál de las siguientes opciones no es un uso habitual de un trigger?", "b) Creación de tablas."));
        banco.add(new Pregunta(216, "Módulo 4", "C4 - TRIGGER", 5, "¿Cuál de las siguientes opciones es un evento que puede activar un trigger?", "b) INSERT"));
        banco.add(new Pregunta(217, "Módulo 4", "C4 - TRIGGER", 6, "¿Cuál de las siguientes opciones es la palabra reservada utilizada para la creación de un trigger?", "a) TRIGGER FIN - MODULOS 1, 2, 3 Y 4"));
        banco.add(new Pregunta(218, "Cierre Módulo 1", "CM1", 1, "¿Qué sublenguaje controla permisos?", "DCL."));
        banco.add(new Pregunta(219, "Cierre Módulo 1", "CM1", 2, "¿Qué ocurre con UPDATE sin WHERE?", "Modifica todas las filas."));
        banco.add(new Pregunta(220, "Cierre Módulo 1", "CM1", 3, "¿Cuál es la diferencia entre DELETE y DROP TABLE?", "DELETE elimina filas; DROP TABLE elimina la tabla y sus datos."));
        banco.add(new Pregunta(221, "Cierre Módulo 1", "CM1", 4, "¿Qué constraint identifica cada fila?", "PRIMARY KEY."));
        banco.add(new Pregunta(222, "Cierre Módulo 1", "CM1", 5, "¿Cómo accedes a productos dentro del esquema compras?", "compras.productos."));
        banco.add(new Pregunta(223, "Cierre Módulo 1", "CM1", 6, "¿Qué hace BETWEEN 10 AND 20?", "Incluye valores desde 10 hasta 20, extremos incluidos."));
        banco.add(new Pregunta(224, "Cierre Módulo 1", "CM1", 7, "¿Qué palabra evita error en DROP TABLE si la tabla no existe?", "IF EXISTS."));
        banco.add(new Pregunta(225, "Cierre Módulo 1", "CM1", 8, "¿Qué estructura inserta resultados de una consulta en otra tabla?", "INSERT INTO ... SELECT ..."));
        banco.add(new Pregunta(226, "Cierre Módulo 2", "CM2", 1, "Longitud luego de reemplazar 'perro' por 'gatito'.", "c) LENGTH(REPLACE(...))."));
        banco.add(new Pregunta(227, "Cierre Módulo 2", "CM2", 2, "Pacientes sin consultas en los últimos 30 días.", "b) NOT EXISTS con filtro de fecha."));
        banco.add(new Pregunta(228, "Cierre Módulo 2", "CM2", 3, "Minutos de 15:30:45.", "a) 30."));
        banco.add(new Pregunta(229, "Cierre Módulo 2", "CM2", 4, "Todos los empleados aunque no tengan departamento.", "b) LEFT JOIN."));
        banco.add(new Pregunta(230, "Cierre Módulo 2", "CM2", 5, "Pedidos únicos por cliente.", "b) COUNT(DISTINCT id_pedido) + GROUP BY."));
        banco.add(new Pregunta(231, "Cierre Módulo 2", "CM2", 6, "Categorías con precio promedio superior a 150.", "d) HAVING AVG(precio) > 150."));
        banco.add(new Pregunta(232, "Cierre Módulo 2", "CM2", 7, "Categoría con producto de precio máximo.", "a) Subconsulta con MAX."));
        banco.add(new Pregunta(233, "Cierre Módulo 2", "CM2", 8, "Departamentos con menos de 3 empleados.", "a) HAVING COUNT(*) < 3."));
        banco.add(new Pregunta(234, "Cierre Módulo 2", "CM2", 9, "Subconsulta correcta para clientes con pedidos > 1000.", "c) IN con subconsulta."));
        banco.add(new Pregunta(235, "Cierre Módulo 2", "CM2", 10, "Cantidad de productos en Electrónica.", "c) COUNT(*) con WHERE."));
        banco.add(new Pregunta(236, "Cierre Módulo 2", "CM2", 11, "Semana del año.", "c) DATE_PART week."));
        banco.add(new Pregunta(237, "Cierre Módulo 2", "CM2", 12, "Caracteres eliminados al usar RIGHT('ordenador',3).", "c) LENGTH(ordenador) - 3."));
        banco.add(new Pregunta(238, "Cierre Módulo 2", "CM2", 13, "Valores distintos de columna1 y columna2.", "b) SELECT DISTINCT columna1, columna2."));
        banco.add(new Pregunta(239, "Cierre Módulo 2", "CM2", 14, "Cada empleado con todos los departamentos.", "a) CROSS JOIN."));
        banco.add(new Pregunta(240, "Cierre Módulo 2", "CM2", 15, "Correos que contienen 'edu.com'.", "d) LIKE '%edu.com%'."));
        banco.add(new Pregunta(241, "Cierre Módulo 2", "CM2", 16, "Reemplazar todos los dígitos de 'abc123' por 'XYZ'.", "a) regexp_replace('abc123','[0-9]+','XYZ')."));
        banco.add(new Pregunta(242, "Cierre Módulo 3", "CM3", 1, "¿Cómo se revierte una transacción al último punto de guardado creado?", "b) ROLLBACK TO SAVEPOINT savepoint_name;"));
        banco.add(new Pregunta(243, "Cierre Módulo 3", "CM3", 2, "¿Cómo asignar una base completa a un tablespace durante su creación?", "b) CREATE DATABASE nombre_db TABLESPACE nombre_tablespace;"));
        banco.add(new Pregunta(244, "Cierre Módulo 3", "CM3", 3, "¿Cómo impedir que un usuario cree tablas en el esquema public?", "a) REVOKE CREATE ON SCHEMA public FROM usuario;"));
        banco.add(new Pregunta(245, "Cierre Módulo 3", "CM3", 4, "Índice adecuado para búsquedas frecuentes por apellido.", "a) CREATE INDEX idx_apellido ON clientes (apellido);"));
        banco.add(new Pregunta(246, "Cierre Módulo 3", "CM3", 5, "¿Qué configurar para registrar errores de nivel ERROR o superior?", "c) log_min_messages = 'error'."));
        banco.add(new Pregunta(247, "Cierre Módulo 3", "CM3", 6, "¿Qué configuración da información detallada sobre errores/transacciones fallidas?", "b) log_error_verbosity = 'verbose'."));
        banco.add(new Pregunta(248, "Cierre Módulo 3", "CM3", 7, "Vista con empleados cuyo salario sea superior a 50000.", "b) CREATE VIEW ... WHERE salario > 50000."));
        banco.add(new Pregunta(249, "Cierre Módulo 3", "CM3", 8, "¿Cómo volver a un SAVEPOINT y omitir solo operaciones erróneas?", "a) ROLLBACK TO SAVEPOINT correct_operations;"));
        banco.add(new Pregunta(250, "Cierre Módulo 3", "CM3", 9, "¿Qué estrategia de rotación usar en logs grandes?", "b) log_rotation_age='1h' y log_rotation_size='50MB'."));
        banco.add(new Pregunta(251, "Cierre Módulo 3", "CM3", 10, "¿Qué comando consulta todos los roles?", "b) SELECT * FROM pg_roles;"));
        banco.add(new Pregunta(252, "Cierre Módulo 3", "CM3", 11, "¿Cómo agregar comentario descriptivo a un tablespace?", "b) COMMENT ON TABLESPACE nombre_tablespace IS 'Comentario descriptivo';"));
        banco.add(new Pregunta(253, "Cierre Módulo 3", "CM3", 12, "¿Cómo crear una vista con departamentos y total de empleados?", "a) JOIN + COUNT(e.id_empleado) + GROUP BY d.nombre."));
        banco.add(new Pregunta(254, "Cierre Módulo 3", "CM3", 13, "¿Qué configuración rota logs cada 24 horas?", "a) log_rotation_age = '1d'."));
        banco.add(new Pregunta(255, "Cierre Módulo 3", "CM3", 14, "¿Cómo crear índice compuesto para nombre y fecha de nacimiento?", "c) CREATE INDEX idx_nombre_fecha ON personas (nombre, fecha_nacimiento);"));
        banco.add(new Pregunta(256, "Cierre Módulo 4", "CM4", 1, "Al momento de eliminar un procedimiento, ¿cuál es la sentencia utilizada para evitar errores?", "a) DROP PROCEDURE IF EXIST nombre_procedimiento (respuesta del cuestionario). Sintaxis real: DROP PROCEDURE IF EXISTS nombre_procedimiento;"));
        banco.add(new Pregunta(257, "Cierre Módulo 4", "CM4", 2, "¿Cuál es la sintaxis correcta para la creación de un procedimiento almacenado?", "d) CREATE PROCEDURE nombre_procedimiento(parámetro) LANGUAGE plpgsql."));
        banco.add(new Pregunta(258, "Cierre Módulo 4", "CM4", 3, "¿Cuántos ELSEIF se pueden agregar a una estructura IF?", "b) No hay límite. En PL/pgSQL se escribe ELSIF."));
        banco.add(new Pregunta(259, "Cierre Módulo 4", "CM4", 4, "La clave RETURNS en una función tiene el propósito de:", "d) Indica el tipo de dato de salida de la función."));
        banco.add(new Pregunta(260, "Cierre Módulo 4", "CM4", 5, "La estructura de un trigger depende de:", "c) Una función."));
        banco.add(new Pregunta(261, "Cierre Módulo 4", "CM4", 6, "¿Qué tipo de estructura de control permite evaluar una expresión True o False?", "d) IF."));
        banco.add(new Pregunta(262, "Cierre Módulo 4", "CM4", 7, "¿Qué tipo de trigger se ejecuta antes de que ocurra un evento?", "b) BEFORE."));
        banco.add(new Pregunta(263, "Cierre Módulo 4", "CM4", 8, "Una variable declarada como CONSTANT:", "b) Debe ser iniciada al ser declarada."));
        banco.add(new Pregunta(264, "Evaluación Final SQL", "Pre-evaluación / Final general", 1, "DDL", "b) DDL (Data Definition Language)"));
        banco.add(new Pregunta(265, "Evaluación Final SQL", "Pre-evaluación / Final general", 2, "INSERT con SERIAL", "a) SQL: INSERT INTO empleados (nombre, apellido, salario, fecha_contratacion) VALUES ('Ana2', 'Ejemplo', 50000, '2024-01-01');"));
        banco.add(new Pregunta(266, "Evaluación Final SQL", "Pre-evaluación / Final general", 3, "DELETE con fecha anterior a 2023-01-01", "b) Para no destruir los datos principales, usamos una transacción: SQL: DELETE FROM clientes WHERE fecha_registro < '2023-01-01';"));
        banco.add(new Pregunta(267, "Evaluación Final SQL", "Pre-evaluación / Final general", 4, "INSERT múltiple", "b) Ya ejecutado arriba: INSERT INTO departamentos (nombre, ubicacion) VALUES (...), (...), (...);"));
        banco.add(new Pregunta(268, "Evaluación Final SQL", "Pre-evaluación / Final general", 5, "Agregar columna", "d) SQL: ALTER TABLE departamentos ADD COLUMN IF NOT EXISTS telefono VARCHAR(20);"));
        banco.add(new Pregunta(269, "Evaluación Final SQL", "Pre-evaluación / Final general", 6, "DCL", "b) DCL"));
        banco.add(new Pregunta(270, "Evaluación Final SQL", "Pre-evaluación / Final general", 7, "BETWEEN", "d) SQL: SELECT * FROM libros WHERE anio_publicacion BETWEEN 2000 AND 2010;"));
        banco.add(new Pregunta(271, "Evaluación Final SQL", "Pre-evaluación / Final general", 8, "BETWEEN + NOT IN", "d) SQL: SELECT nombre, fecha_nacimiento AS fecha FROM estudiantes WHERE fecha_nacimiento BETWEEN '1995-01-01' AND '2000-12-31' AND nom_carrera NOT IN ('Ingeniería', 'Medicina', 'Arquitectura');"));
        banco.add(new Pregunta(272, "Evaluación Final SQL", "Pre-evaluación / Final general", 9, "BETWEEN + IN + AND", "c) SQL: SELECT titulo, anio_publicacion FROM libros WHERE anio_publicacion BETWEEN 2015 AND 2020 AND id_autor IN (1, 3, 5) AND calificacion >= 4;"));
        banco.add(new Pregunta(273, "Evaluación Final SQL", "Pre-evaluación / Final general", 10, "Expresión regular", "c) En PostgreSQL usamos ~ para regex. Para evitar diferencias por \\d, usamos [0-9] en la práctica: SQL: SELECT * FROM productos WHERE codigo ~ '^[A-Za-z][0-9]{4}$';"));
        banco.add(new Pregunta(274, "Evaluación Final SQL", "Pre-evaluación / Final general", 11, "LIKE contiene \"Juan\"", "a) SQL: SELECT * FROM empleados WHERE nombre LIKE '%Juan%';"));
        banco.add(new Pregunta(275, "Evaluación Final SQL", "Pre-evaluación / Final general", 12, "SUM por producto", "b) SQL: SELECT producto, SUM(cantidad) AS cantidad_total FROM ventas GROUP BY producto;"));
        banco.add(new Pregunta(276, "Evaluación Final SQL", "Pre-evaluación / Final general", 13, "HAVING", "b) SQL: SELECT producto, SUM(cantidad) AS cantidad_total FROM ventas GROUP BY producto HAVING SUM(cantidad) > 10;"));
        banco.add(new Pregunta(277, "Evaluación Final SQL", "Pre-evaluación / Final general", 14, "Orden correcto", "b) GROUP BY -> HAVING -> ORDER BY SQL: SELECT producto, SUM(cantidad) AS cantidad_total FROM ventas GROUP BY producto HAVING SUM(cantidad) > 0 ORDER BY cantidad_total DESC;"));
        banco.add(new Pregunta(278, "Evaluación Final SQL", "Pre-evaluación / Final general", 15, "PostgreSQL", "b) Sistema de gestión de bases de datos relacional y de código abierto."));
        banco.add(new Pregunta(279, "Evaluación Final SQL", "Pre-evaluación / Final general", 16, "Precio promedio de productos cuyo total vendido supera 100", "Ninguna opción era 100% correcta; SQL correcto: SELECT producto AS prod, AVG(precio) AS precio_promedio FROM ventas GROUP BY producto HAVING SUM(cantidad) > 100;"));
        banco.add(new Pregunta(280, "Evaluación Final SQL", "Pre-evaluación / Final general", 17, "5 fechas más recientes sin repetir", "a) SQL: SELECT DISTINCT fecha_pedido AS fecha FROM pedidos ORDER BY fecha_pedido DESC LIMIT 5;"));
        banco.add(new Pregunta(281, "Evaluación Final SQL", "Pre-evaluación / Final general", 18, "LEFT JOIN", "d) Todas las filas de empleados + coincidencias de direcciones. SQL: SELECT a.nombre, b.direccion FROM empleados a LEFT JOIN direcciones b ON a.id_empleado = b.id_empleado;"));
        banco.add(new Pregunta(282, "Evaluación Final SQL", "Pre-evaluación / Final general", 19, "Pregunta 19 no disponible en el material original", "La pregunta 19 no apareció en el material original recuperado."));
        banco.add(new Pregunta(283, "Evaluación Final SQL", "Pre-evaluación / Final general", 20, "RIGHT JOIN", "b) Todas las filas de productos + pedidos coincidentes. SQL: SELECT p.producto, o.fecha FROM pedidos o RIGHT JOIN productos p ON o.id_producto = p.id_producto;"));
        banco.add(new Pregunta(284, "Evaluación Final SQL", "Pre-evaluación / Final general", 21, "FULL JOIN", "b) Todas las filas de ambos lados; NULL cuando no hay coincidencia. SQL: SELECT p.producto, s.stock FROM productos p FULL JOIN inventario s ON p.id_producto = s.id_producto;"));
        banco.add(new Pregunta(285, "Evaluación Final SQL", "Pre-evaluación / Final general", 22, "Característica distintiva de PostgreSQL", "b) Permite crear tipos y dominios personalizados. SQL: DROP DOMAIN IF EXISTS codigo_demo;"));
        banco.add(new Pregunta(286, "Evaluación Final SQL", "Pre-evaluación / Final general", 23, "Precio mayor que el promedio global", "d) SQL: SELECT producto FROM ventas v1 WHERE precio > (SELECT AVG(precio) FROM ventas);"));
        banco.add(new Pregunta(287, "Evaluación Final SQL", "Pre-evaluación / Final general", 24, "LEFT + RIGHT + CONCAT", "d) SQL: SELECT CONCAT(LEFT(nombre, 3), RIGHT(apellido, 2)) AS \"user\" FROM empleados;"));
        banco.add(new Pregunta(288, "Evaluación Final SQL", "Pre-evaluación / Final general", 25, "REPLACE + LENGTH", "c) SQL: SELECT LENGTH(REPLACE(descripcion, 'nuevo', 'antiguo')) AS longitud FROM productos;"));
        banco.add(new Pregunta(289, "Evaluación Final SQL", "Pre-evaluación / Final general", 26, "Crear correo", "a) SQL: SELECT CONCAT(nombre, '.', apellido, '@estudiantes.edu.uy') AS correo FROM estudiantes;"));
        banco.add(new Pregunta(290, "Evaluación Final SQL", "Pre-evaluación / Final general", 27, "Quitar últimos 3 caracteres y reemplazar a -> x", "a) SQL: SELECT REPLACE( LEFT(nombre_cliente, LENGTH(nombre_cliente) - 3), 'a', 'x' ) AS nombre_modificado FROM clientes;"));
        banco.add(new Pregunta(291, "Evaluación Final SQL", "Pre-evaluación / Final general", 28, "Antigüedad en años", "b) SQL: SELECT DATE_PART('year', CURRENT_DATE) - DATE_PART('year', fecha_contratacion) AS antiguedad FROM empleados;"));
        banco.add(new Pregunta(292, "Evaluación Final SQL", "Pre-evaluación / Final general", 29, "Vista con nombre y total de pedidos", "c) SQL: DROP VIEW IF EXISTS vista_total_pedidos;"));
        banco.add(new Pregunta(293, "Evaluación Final SQL", "Pre-evaluación / Final general", 30, "WHERE", "b) SQL: SELECT * FROM empleados WHERE salario > 50000;"));
        banco.add(new Pregunta(294, "Evaluación Final SQL", "Pre-evaluación / Final general", 31, "Una sola vista para nombre_cliente y monto_total_compras", "b) Creamos vista_ventas con la información ya integrada. SQL: DROP VIEW IF EXISTS vista_ventas;"));
        banco.add(new Pregunta(295, "Evaluación Final SQL", "Pre-evaluación / Final general", 32, "Otorgar un rol a un usuario", "c) Estos comandos requieren privilegios administrativos. Se dejan comentados para que el script no falle:"));
        banco.add(new Pregunta(296, "Evaluación Final SQL", "Pre-evaluación / Final general", 33, "REVOKE SELECT", "d) Ejemplo administrativo: REVOKE SELECT ON ventas FROM rol_reportes;"));
        banco.add(new Pregunta(297, "Evaluación Final SQL", "Pre-evaluación / Final general", 34, "Roles", "c) Permiten agrupar y gestionar permisos centralizadamente."));
        banco.add(new Pregunta(298, "Evaluación Final SQL", "Pre-evaluación / Final general", 35, "Transacciones", "a) Agrupan varias operaciones en una unidad de trabajo."));
        banco.add(new Pregunta(299, "Evaluación Final SQL", "Pre-evaluación / Final general", 36, "Confirmar transacción", "a) COMMIT"));
        banco.add(new Pregunta(300, "Evaluación Final SQL", "Pre-evaluación / Final general", 37, "SAVEPOINT", "a) El INSERT se revierte; el UPDATE queda y se confirma. Se ejecuta dentro de una transacción para mostrarlo. SQL: UPDATE cuentas SET saldo = saldo - 100 WHERE id = 1;"));
        banco.add(new Pregunta(301, "Evaluación Final SQL", "Pre-evaluación / Final general", 38, "CREATE DATABASE parámetros opcionales", "d) Todas son correctas"));
        banco.add(new Pregunta(302, "Evaluación Final SQL", "Pre-evaluación / Final general", 39, "Cambiar propietario de una base", "b) ALTER DATABASE nombre OWNER TO nuevo_propietario;"));
        banco.add(new Pregunta(303, "Evaluación Final SQL", "Pre-evaluación / Final general", 40, "Eliminar tabla", "c) DROP TABLE nombre_tabla;"));
        banco.add(new Pregunta(304, "Evaluación Final SQL", "Pre-evaluación / Final general", 41, "Ubicación de archivos de log", "a) log_directory Ejemplo de consulta segura:"));
        banco.add(new Pregunta(305, "Evaluación Final SQL", "Pre-evaluación / Final general", 42, "Habilitar recolección de logs", "d) logging_collector"));
        banco.add(new Pregunta(306, "Evaluación Final SQL", "Pre-evaluación / Final general", 43, "Índice para valores únicos", "d) B-tree UNIQUE y PRIMARY KEY usan B-tree por defecto."));
        banco.add(new Pregunta(307, "Evaluación Final SQL", "Pre-evaluación / Final general", 44, "Índice útil para búsqueda de texto", "c) GIN Ejemplo nativo con full-text search:"));
        banco.add(new Pregunta(308, "Evaluación Final SQL", "Pre-evaluación / Final general", 45, "Tablespace", "a) Espacio/ubicación física donde PostgreSQL puede almacenar objetos."));
        banco.add(new Pregunta(309, "Evaluación Final SQL", "Pre-evaluación / Final general", 46, "Propósito de tablespace", "d) Organizar/distribuir datos en diferentes discos o ubicaciones. IMPORTANTE: crear TABLESPACE requiere permisos y una carpeta física"));
        banco.add(new Pregunta(310, "Evaluación Final SQL", "Pre-evaluación / Final general", 47, "PL/pgSQL", "a) Funciones, triggers, variables, control de flujo y excepciones."));
        banco.add(new Pregunta(311, "Evaluación Final SQL", "Pre-evaluación / Final general", 48, "Integración PL/pgSQL + SQL", "d) PL/pgSQL extiende SQL con lógica procedural."));
        banco.add(new Pregunta(312, "Evaluación Final SQL", "Pre-evaluación / Final general", 49, "Fecha y hora con microsegundos", "b) TIMESTAMP"));
        banco.add(new Pregunta(313, "Evaluación Final SQL", "Pre-evaluación / Final general", 50, "%ROWTYPE", "c) Variable con la estructura completa de una fila de productos. Creamos una función de demostración. SQL: CREATE OR REPLACE FUNCTION obtener_producto_demo(p_id INTEGER) RETURNS productos LANGUAGE plpgsql AS $$ DECLARE v_producto productos%ROWTYPE;"));
        banco.add(new Pregunta(314, "Evaluación Final SQL", "Pre-evaluación / Final general", 51, "Condicional", "c) \"Entre 5 y 10\" para p_num = 10"));
        banco.add(new Pregunta(315, "Evaluación Final SQL", "Pre-evaluación / Final general", 52, "Sumar del 1 al 10", "a, según las imágenes enviadas."));
        banco.add(new Pregunta(316, "Evaluación Final SQL", "Pre-evaluación / Final general", 53, "Procedimiento incrementar contador", "c) SQL: CREATE OR REPLACE PROCEDURE incrementar_contador(p_id INTEGER) LANGUAGE plpgsql AS $$ BEGIN UPDATE contadores SET valor = valor + 1 WHERE id = p_id;"));
        banco.add(new Pregunta(317, "Evaluación Final SQL", "Pre-evaluación / Final general", 54, "CALL procedimiento", "c) SQL: CALL incrementar_contador(1);"));
        banco.add(new Pregunta(318, "Evaluación Final SQL", "Pre-evaluación / Final general", 55, "DROP FUNCTION con firma", "c) Creamos una función de prueba y luego la eliminamos correctamente. SQL: CREATE OR REPLACE FUNCTION calcular_total(NUMERIC, NUMERIC) RETURNS NUMERIC LANGUAGE sql AS $$ SELECT $1 + $2;"));
        banco.add(new Pregunta(319, "Evaluación Final SQL", "Pre-evaluación / Final general", 56, "Trigger BEFORE INSERT", "c) En PostgreSQL moderno se usa EXECUTE FUNCTION. SQL: CREATE TABLE log_ventas ( id_log SERIAL PRIMARY KEY, id_cliente INTEGER, id_producto INTEGER, cantidad INTEGER, fecha_log TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP );"));
        banco.add(new Pregunta(320, "Evaluación Final SQL", "Pre-evaluación / Final general", 57, "CHAR vs VARCHAR", "c) CHAR = longitud fija VARCHAR = longitud variable SQL: CREATE TABLE ejemplo_texto ( codigo CHAR(5), descripcion VARCHAR(50) );"));
        banco.add(new Pregunta(321, "Evaluación Final SQL", "Pre-evaluación / Final general", 58, "Evento que NO activa trigger DML común", "a) SELECT"));
        banco.add(new Pregunta(322, "Evaluación Final SQL", "Pre-evaluación / Final general", 59, "Trigger que registra cada INSERT de empleados", "c) AFTER INSERT"));
        banco.add(new Pregunta(323, "Evaluación Final SQL", "Pre-evaluación / Final general", 60, "Crear base y cambiar propietario", "d) Debe ejecutarse desde otra base, por ejemplo \"postgres\": CREATE DATABASE my_database; ALTER DATABASE my_database OWNER TO db_owner; No se ejecuta aquí porque no corresponde crear/cambiar la base"));
        return banco;
    }

    public static void main(String[] args) {
        List<Pregunta> banco = cargarPreguntas();
        String grupoAnterior = "";
        String seccionAnterior = "";

        for (Pregunta p : banco) {
            if (!p.grupo.equals(grupoAnterior)) {
                System.out.println("\n============================================================");
                System.out.println(p.grupo.toUpperCase());
                System.out.println("============================================================");
                grupoAnterior = p.grupo; seccionAnterior = "";
            }
            if (!p.seccion.equals(seccionAnterior)) {
                System.out.println("\n--- " + p.seccion + " ---");
                seccionAnterior = p.seccion;
            }
            System.out.println("\n[" + p.id + "] Pregunta " + p.numero + ": " + p.enunciado);
            System.out.println("Respuesta: " + p.respuesta);
        }
        System.out.println("\nTotal de preguntas: " + banco.size());
    }
}
